version: "3.9"

services:
  pg-fastapi:
    image: postgres:16
    container_name: pg-fastapi
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_db"]
      interval: 5s
      timeout: 3s
      retries: 10


  # FastAPI Application
  web:
    build: .
    container_name: fastapi-app
    restart: always
    depends_on:
      pg-fastapi:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["bash", "start.sh"]
    volumes:
      - .:/code

  # 🧩 Add this new pgAdmin service below
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env # this file contains PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
    depends_on:
      - pg-fastapi

volumes:
  pg_data:
