version: "3.9"

services:
  # -----------------------------------------------------------------
  # PostgreSQL Database
  # -----------------------------------------------------------------
  db:
    image: postgres:15
    container_name: pg-fastapi
    restart: always
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
      POSTGRES_DB: task_db
    volumes:
      - pgdata_fastapi:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  # -----------------------------------------------------------------
  # pgAdmin (Web UI for PostgreSQL)
  # -----------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-fastapi
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PGADMIN_LISTEN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin


  # -----------------------------------------------------------------
  # FastAPI Application
  # -----------------------------------------------------------------
  api:
    build: .
    container_name: fastapi-task-api
    restart: always
    env_file:
      - .env                     # loads SECRET_KEY, DB URL, etc.
    volumes:
      - ./:/app                  # live-reload during dev
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - fastapi_net

volumes:
  pgdata_fastapi:
  pgadmin_data:

networks:
  fastapi_net:
    driver: bridge